### ISSUE TITLE
No reverse or button 7

### ISSUE THREAD

**Issue by gptech2444** [JamoDevNich/G29-Arduino-USB-Adapter#1]
Hi, Just finished wiring this up to a new G29 shifter, everything works except for reverse.
I can't get button 7 to light up even with shorting pin 10 to GND with or without the shifter connected.
Thanks.
edit: looks like the pro micro is faulty. pin 10 has short to gnd.

**Comment by JamoDevNich** [comment]
Since pin 10 is being used as a normal input, it should be high to register as a button press iirc. If that pin's gone toast, any other input on your pro micro would work fine (e.g. pin 5), and in code change `SHIFTER_BUTTON` from `10` to the new pin

https://github.com/JamoDevNich/G29-Arduino-USB-Adapter/blob/04a80f2cb30a43018aa83b239b2fef155afe6f90/G29_Arduino_USB_Adapter/G29_Arduino_USB_Adapter.ino#L7

There is a serial output running at 115200 baud which prints some diagnostic info, that should also help with checking if it's working correctly.

Could you let me know if you connected both 'VCC' connections (shown in the table on the homepage) from your pro micro to the db9 connector? I believe both are required

**Comment by gptech2444** [comment]
I changed to pin 9 and this worked but it kept changing modes whenever reverse was selected. 
I changed the code so stayed only in gamepad mode by changing the 1 to a 0 and it's been working great. I don't need the other modes. And VCC is connected to pin 3 and 7.
[      else currentOutputModeSelected += 1;](https://github.com/JamoDevNich/G29-Arduino-USB-Adapter/blob/04a80f2cb30a43018aa83b239b2fef155afe6f90/G29_Arduino_USB_Adapter/G29_Arduino_USB_Adapter.ino#L106)
